gpiolib-cdev: add missing braces in GPIO_SET_DEBOUNCE_IOCTL case
The lack of braces caused build failures when compiling the kernel with
Clang for Android.

gpiolib-cdev.c:2684:3: error: expected expression
 2684 |                 struct gpioline_debounce linedebounce;

Signed-off-by: Javier Viguera <javier.viguera@digi.com>