arm: mach-imx: add conditional compilation for 6ULL
Otherwise, the code does not compile if CONFIG_SOC_IMX6ULL is not defined, even
when this file is also used for other platforms:

arch/arm/mach-imx/built-in.o: In function `imx6ul_cpuidle_init':
platform-imx-dma.c:(.init.text+0xa08): undefined reference to `mx6ull_lpm_wfi_end'
platform-imx-dma.c:(.init.text+0xa0c): undefined reference to `mx6ull_lpm_wfi_start'
platform-imx-dma.c:(.init.text+0xa10): undefined reference to `mx6ull_lpm_wfi_end'
platform-imx-dma.c:(.init.text+0xa14): undefined reference to `mx6ull_lpm_wfi_start'
platform-imx-dma.c:(.init.text+0xa18): undefined reference to `imx6ull_low_power_idle'
platform-imx-dma.c:(.init.text+0xa20): undefined reference to `imx6ull_low_power_idle'
Makefile:933: recipe for target 'vmlinux' failed

This problem was introduced in e70b4ce83cb3a83e0dad7ae48f58df6b88d8d677.

Signed-off-by: Diaz de Grenu, Jose <Jose.DiazdeGrenu@digi.com>