uapi: remove CONFIG_COMPAT reference from NXP headers
Certain headers added by NXP reference CONFIG_COMPAT from the
uapi and this produces a leak error:

  error: include/uapi/linux/fmd/Peripherals/fm_ioctls.h: leak CONFIG_COMPAT to user-space
  error: include/uapi/linux/fmd/Peripherals/fm_port_ioctls.h: leak CONFIG_COMPAT to user-space

Such ifdefs should be moved to the user space application when
calling the functions.

Signed-off-by: Hector Palacios <hector.palacios@digi.com>