ARM64: configs: ccimx8: remove PHY_MIXEL_LVDS_PHY support
Both PHY_MIXEL_LVDS and PHY_MIXEL_LVDS_PHY configurations enable drivers
called "mixel-lvds-phy", causing the following boot time message:

    Error: Driver 'mixel-lvds-phy' is already registered, aborting...

Remove PHY_MIXEL_LVDS_PHY following implementation in imx_v8_defconfig from
NXP.

Signed-off-by: Gonzalo Ruiz <Gonzalo.Ruiz@digi.com>