imx6ul: enable (by selecting) HAVE_IMX_BUSFREQ
In NXP's 'lf-5.15.71-2.2.0' release, commit
682cd2e8566d86cf20b82ce582fa891d37c10aec, encapsulates some IMX busfreq
functionality between CONFIG_HAVE_IMX_BUSFREQ guards. That symbol is
hidden, so the only way to enable it is by selecting it. This commit
enables it for SOC_IMX6 platforms.

This fixes the build for the CCIMX6UL, that got broken after the merge
of the new NXP release:

arm-linux-gnueabi-ld: arch/arm/mach-imx/busfreq-imx.o: in function `busfreq_reboot_notifier_event':
busfreq-imx.c:(.text+0x8): undefined reference to `request_bus_freq'

Signed-off-by: Javier Viguera <javier.viguera@digi.com>