ARM: configs: ccimx6sbc: remove CONFIG_MXC_CAMERA_OV5640_V2
This commit removes the CONFIG_MXC_CAMERA_OV5640_V2 option from the ccimx6sbc
configuration. This setting is only relevant for i.MX6UL/ULL/SX/SL/SLL
processors and is not applicable to the i.MX6Q platform used in ccimx6sbc.

Removing this option avoids the following boot-time error caused by conflicting
driver registration:
    Error: Driver 'ov5640' is already registered, aborting...

https://onedigi.atlassian.net/browse/DEL-9759

Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>