spi: stm32-qspi: Fix stm32_qspi_transfer_one_message() error path
The patch a557fca630cc: "spi: stm32_qspi: Add transfer_one_message()
spi callback" from Aug 23, 2022, leads to the following Smatch static
checker warning:

drivers/spi/spi-stm32-qspi.c:627 stm32_qspi_transfer_one_message()
error: uninitialized symbol 'ret'.Fix the following Smatch static checker warning:

Fixes: bc4a7566838a ("spi: stm32_qspi: Add transfer_one_message() spi callback")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Patrice Chotard <patrice.chotard@foss.st.com>
Change-Id: Ibdfb2ea5ab46cb944457901dc651ea46fbb41005
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/linux-stm32/+/264157
Reviewed-by: CIBUILD <MDG-smet-aci-builds@list.st.com>