brcmfmac: fix compiler error and warning by file system API
error:
drivers/net/wireless/broadcom/brcm80211/brcmfmac/debug.c: In function ‘brcmf_debug_del_dir_file’:
drivers/net/wireless/broadcom/brcm80211/brcmfmac/debug.c:128:36: error: ‘struct dentry’ has no member named ‘d_subdirs’
  list_for_each_entry(child, &parent->d_subdirs, d_child) {
                                    ^

drivers/net/wireless/broadcom/brcm80211/brcmfmac/debug.c:128:49: error: ‘struct dentry’ has no member named ‘d_child’; did you mean ‘d_children’?
  list_for_each_entry(child, &parent->d_subdirs, d_child) {
                                                 ^

warning: no previous prototype for ‘brcmf_debug_cal_avail_space’ [-Wmissing-prototypes]
 unsigned long long brcmf_debug_cal_avail_space(struct brcmf_bus *bus, const char *cal_path)

1. v6.8 changed memebers in the dentry structure, so it needs to use
hlist_for_each_entry() to replace of list_for_each_entry.

2. vfs_unlink
* before v5.12
int vfs_unlink(struct inode *dir, struct dentry *dentry, struct inode **delegated_inode)
* v5.13~v6.2.x
int vfs_unlink(struct user_namespace *mnt_userns, struct inode *dir,
	       struct dentry *dentry, struct inode **delegated_inode)
* v6.3+
int vfs_unlink(struct mnt_idmap *idmap, struct inode *dir,
	       struct dentry *dentry, struct inode **delegated_inode)

Fixes SWLINUX-5493

Signed-off-by: Shelley Yang <shelley.yang@infineon.com>

(cherry picked from commit e68a16e491ce8e2452a5ef0796423cf45b287740)

Co-authored-by: Shelley Yang <shelley.yang@infineon.com>