mtdcrypt: fix various compilation issues
Fix a couple of warnings and the following compilation error:

drivers/mtd/mtdcrypt.c: In function ‘mtdcrypt_get_key_from_part’:
drivers/mtd/mtdcrypt.c:629:8: error: passing argument 4 of ‘mtd_read’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  629 |        &retlen, keyblob_str)) {
      |        ^~~~~~~
      |        |
      |        int *

https://onedigi.atlassian.net/browse/DEL-7584

Signed-off-by: Gonzalo Ruiz <Gonzalo.Ruiz@digi.com>
(cherry picked from commit a20fe473f7fae6730ee66a33e6c39c4005fe4143)
Signed-off-by: Javier Viguera <javier.viguera@digi.com>